.\" BMonkey manpage.
.\" Copyright © 2014 Juan Ángel Moreno Fernández
.\"
.TH BMonkey "19" "October 2014" "" ""
.SH NAME
BMonkey \- An arcade frontend for GNU/Linux

.SH SYNOPSIS
.B bmonkey

.SH DESCRIPTION
.B BMonkey
is an arcade frontend.

It support a wide range of systems and a wide range of emulators driven by
console parameters.

BMonkey is a free project licensed under the GNU General Public License and is
written in C++ using SFML libraries.

.SH BUGS
Please * bmonkey bug tracker at Sourceforge.net
.TP
\fIhttp://sourceforge.net/projects/gelide\fP
.TP
or directly to
.TP
\fIgelide.prj@gmail.com\fP.

.SH CONTACT
Juan Ángel Moreno Fernández <\fIjamf@users.sourceforge.net\fP>
.TP
\fIhttp://gelide.sourceforge.net\fP

.SH AUTHOR
Written by Juan Ángel Moreno Fernández <gelide.prj@gmail.com>
